#! /usr/bin/env perl -w
use strict;
use warnings;

my %certfiles;

foreach my $DIR ( <certs.*> ) {
    chdir $DIR || die "Can't chdir $DIR, $!";
    foreach my $FILE ( <*> ) {
	$certfiles{$FILE} = 1;
    }
    chdir ".." || die "Can't chdir up from $DIR, $!";
}
foreach my $FILE ( sort keys %certfiles ) {
    print "$FILE\n"
	if -f "certs.apple/$FILE"
	  && -f "certs.google/$FILE"
	  && -f "certs.gtrust/$FILE"
	  && -f "certs.microsoft/$FILE"
	  && ! -f "certs.akamai/$FILE";
}
