#! /bin/bash
LSG=lsg-east.akamai.com

redigest() {
    sha=$(openssl x509 -fingerprint -sha256 -noout <$1)
    sha=$(echo $sha | sed -e s/.*Fingerprint=// -e s/://g)
    openssl x509 -text <$1 >$sha
    rm $1
}

which tidy >/dev/null || { echo 'Need tidy installed' ; exit 1 ; }

# Write out akamai-permissive set, akamai not-in-any-set
scp -q ${LSG}:/a/tools/metadata/ghostdir.ca.list/global_server.xml .
rm -rf certs.akamai
mkdir certs.akamai
cd certs.akamai
../split-permissive.py ../global_server.xml
for CERT in * ; do
    redigest $CERT
done
echo Permissive-set has $(ls | wc -l)
cd ..

rm -rf certs.aka-gs
mkdir certs.aka-gs
cd certs.aka-gs
../split-gs.py ../global_server.xml
for CERT in * ; do
    redigest $CERT
done
echo Global-server has $(ls | wc -l)
cd ..

rm -rf trust_stores_as_pem*
curl --silent --show-error --remote-name https://nabla-c0d3.github.io/trust_stores_observatory/trust_stores_as_pem.tar.gz
mkdir trust_stores_as_pem
cd trust_stores_as_pem
tar zxf ../trust_stores_as_pem.tar.gz
cd ..

for WHO in apple google microsoft mozilla ; do
    rm -rf certs.$WHO
    mkdir certs.$WHO
    cd certs.$WHO
    ../split-pem.pl <../trust_stores_as_pem/${WHO}*.pem
    for CERT in * ; do
	redigest $CERT
    done
    echo $WHO has $(ls |wc -l)
    cd ..
done


# Scrape the Chrome root store.  Sigh :(
# Also understands the output of tidy.  Double sigh.
# Wish I could get "export as CSV" working.
rm -rf certs.gtrust
mkdir certs.gtrust
curl --silent --show-error https://g.co/chrome/root-store \
    | tidy -q 2>/dev/null \
    | perl -n -e 'print $1, "\n" if /^([0-9A-f]{64})<.td>$/;' | while read FILE ; do
    # Multiple files will be identical, so okay to overwrite.
    # If file doesn't exist, an error will print.
    cp certs.*/$FILE certs.gtrust
done
echo Chrome root store has $(ls certs.gtrust | wc -l)
