#! /usr/bin/env perl
use strict;
use warnings;

my %certfiles;

foreach my $DIR ( <certs.*> ) {
    chdir $DIR || die "Can't chdir $DIR, $!";
    foreach my $FILE ( <*> ) {
	$certfiles{$FILE} = 1;
    }
    chdir ".." || die "Can't chdir up from $DIR, $!";
}

my @missing = grep {
    -f "certs.apple/$_"
    && -f "certs.google/$_"
    && -f "certs.microsoft/$_"
    && -f "certs.mozilla/$_"
    && ! -f "certs.akamai/$_" } sort keys %certfiles;

foreach my $FILE ( @missing ) {
    print "$FILE\n";
}
