#! /bin/bash

OUT=akamai-trust-store.md
REPO=akamai-certificate-store

(
echo "# Akamai's Certificate Store"
echo
echo - Last updated: $(date).
echo - There are $(ls certs.akamai | wc -l) entries.
echo - Certs below are listed in order of their digest value\;
echo we know this is not incredibly useful.
echo
echo Links below point to the full certificate on \`https://crt.sh\`.
echo
) >$OUT

CRTSH="https://crt.sh?q="

ls certs.akamai | while read FILE ; do
    # Can't just use "grep" because it gets too much
    openssl x509 -noout -subject -serial -enddate -fingerprint <certs.akamai/$FILE >/tmp/mgh$$
    NAME=$(sed -n -e 's/subject=//p' /tmp/mgh$$)
    SERIAL=$(sed -n -e 's/serial=//p' /tmp/mgh$$)
    EXPIRES=$(sed -n -e 's/notAfter=//p' /tmp/mgh$$)
    FPRINT=$(sed -n -e 's/SHA1 Fingerprint=//p' /tmp/mgh$$)
    rm /tmp/mgh$$
    echo "- Name: ${NAME}  "
    echo "  Fingerprint: ${FPRINT}  "
    echo "  Serial:  ${SERIAL}  "
    echo "  Expires:  ${EXPIRES}  "
    echo "  ${CRTSH}${FILE}"
    echo
done >>$OUT

test -d ../$REPO || exit 0

cp $OUT ../$REPO/.
cd ../$REPO
git commit -m "Automatic update" $OUT
git push
