#! /bin/bash

CW="5%"
exec >index.html

# Make a single list of certs
rm -rf all
mkdir all
for I in certs.* ; do
    case $I in
    certs.akamai) ;;
    *) cp -n $I/* all ;;
    esac
done

cat <<EOF
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Trust store comparison</title>
    <script src="jquery.min.js"></script>
    <script src="jquery.tablesorter.min.js"></script>
    <script>\$(function() { \$("#myTable").tablesorter();})</script>
    <style>
      table {
        text-align: left;
        position: relative;
        border-collapse: collapse;
      }
      th, td {
        padding: 0.25rem;
      }
      tr.heading th {
        background: grey;
        color: white;
      }
      th {
        background: white;
        position: sticky;
        top: 0; /* Don't forget this, required for the stickiness */
        box-shadow: 0 2px 2px -1px rgba(0, 0, 0, 0.4);
      }
    </style>
  </head>

  <body>
    <h1>Trust Store Comparison</h1>
    <p>This page generated at $(date) from scripts at
    <a href="https://git.source.akamai.com/users/rsalz/repos/trust-store-comparison/browse">https://git.source.akamai.com/users/rsalz/repos/trust-store-comparison/browse</a>.
    </p>
    <p>Click on a column header to sort by that column.
    Double-Click to reverse-sort. Column headings:</p>
    <ul>
      <li>aka-cps - The "permissive set" from CPS-ENGINE</li>
      <li>aka-gs - All certs in global-server.xml not in a set</li>
      <li>akamai - The "permissive set"</li>
      <li>apple - Apple's trust store</li>
      <li>google - from the Android Open Source Project</li>
      <li>gtrust - the new (2021) Chrome trust store</li>
      <li>microsoft - Microsoft's trust store</li>
      <li>mozilla - Firefox's trust store</li>
    </ul>

    <table id="myTable" class="tablesorter" border='1'>
      <thead>
        <tr class="heading">
          <th>Issuer<br>&#8597; ($(ls all | wc -l))</th>
EOF

for I in certs.* ; do
  WHO=$(echo $I | sed -e s/certs.//)
  echo "          <th>$WHO<br>&#8597; ($(ls $I | wc -l))</th>"
done
echo "          <th>#<br>&#8597; </th>"
echo "        </tr>"
echo "      </thead>"
echo
echo "      <tbody>"

CRTSH="https://crt.sh?q="
ls all | while read FILE ; do
    echo "        <tr>"
    ISS=$(grep Issuer all/$FILE | sed -e 's/.*Issuer: //')
    COUNT=0
    echo "          <td><a target=\"_blank\" href=\"$CRTSH$FILE\">$ISS</a></td>"
    for C in certs.* ; do
        VAL="-"
        if test -f $C/$FILE ; then
            VAL="Y"
            : $((COUNT++))
        fi
        echo "          <td width=\"$CW\">$VAL</td>"
    done
    echo "          <td width=\"$CW\">$COUNT</td>"
    echo "        </tr>"
done

echo "      </tbody>"
echo "    </table>"
echo "  </body>"
echo "</html>"

rm -rf all
