#! /bin/bash

exec >deleted-certs.html
test "x$1" = "x-all" && all="-all"

cat <<EOF
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>To Be Deleted from Akamai permissive-set</title>
  </head>

  <body>
    <h1>To Be Deleted from Akamai permissive-set</h1>
    <p>This page generated at $(date).<br>
    Number deleted = $(./list-deleted ${all} | wc -l)</p>
EOF

echo "  <ul>"
(
    CRTSH="https://crt.sh?q="
    ./list-deleted ${all} | while read FILE ; do
	ISS=$(grep Issuer: certs.akamai/$FILE | sed -e 's/.*Issuer: //')
	COUNT=0
	echo "     <li><a target=\"_blank\" href=\"$CRTSH$FILE\">$ISS</a></li>"
    done
) | sort '-t>' -k 3

echo "  </ul>"
echo "</html>"
