#! /usr/bin/env perl
use strict;
use warnings;

use File::Path qw( rmtree );
use File::Compare;
use File::Copy;
use Getopt::Long qw(GetOptions);

my $now = `date`;
my $link = "https://git.source.akamai.com/users/rsalz/repos/trust-store-comparison/browse";
my $CRTSH = "https://crt.sh?q=";
my $md = "akamai-certificate-store.md";
my $repo = '../akamai-certificate-store';
my $justwrong = 0;

GetOptions(
    'wrong|w' => \$justwrong
) or die "Only option is -w\n";

# HTTP <head> field for sortable tables.
my $head = <<EOF;
  <head>
    <title>Trust store comparison</title>
    <script src="jquery.min.js"></script>
    <script src="jquery.tablesorter.min.js"></script>
    <script>\$(function() { \$("#myTable").tablesorter();})</script>
    <style>
      table {
        text-align: left;
        position: relative;
        border-collapse: collapse;
      }
      th, td {
        padding: 0.25rem;
      }
      tr.heading th {
        background: grey;
        color: white;
      }
      th {
        background: white;
        position: sticky;
        top: 0; /* Don't forget this, required for the stickiness */
        box-shadow: 0 2px 2px -1px rgba(0, 0, 0, 0.4);
      }
    </style>
  </head>
EOF

# Table cells for cert (not)present columns.
my $CW = '4%';
my $PRESENT = "<td width=\"$CW\" bgcolor=\"green\">Y</td>";
my $NOTPRESENT = "<td width=\"$CW\" bgcolor=\"grey\">-</td>";

# Entries for various special status values.
my $MISSING = "&nbsp;&nbsp;<EM>missing</EM>";
my $LEGACY = "&nbsp;&nbsp;<EM>grandfathered</EM>";
my $WRONG = "&nbsp;&nbsp;<EM>wrong</EM>";

# List of certs that are out of policy, but grandfathered.
my %grandfathered = (
    '1465FA205397B876FAA6F0A9958E5590E40FCC7FAA4FB7C2C8677521FB5FB658' => 1,
    '2399561127A57125DE8CEFEA610DDF2FA078B5C8067F4E828290BFB860E84B3C' => 1,
    '4348A0E9444C78CB265E058D5E8944B4D84F9662BD26DB257F8934A443C70161' => 1,
    '4B03F45807AD70F21BFC2CAE71C9FDE4604C064CF5FFB686BAE5DBAAD7FDD34C' => 1,
    '568D6905A2C88708A4B3025190EDCFEDB1974A606A13C6E5290FCB2AE63EDAB5' => 1,
    '62DD0BE9B9F50A163EA0F8E75C053B1ECA57EA55C8688F647C6881F2C8357B95' => 1,
    '7431E5F4C3C1CE4690774F0B61E05440883BA9A01ED00BA6ABD7806ED3B118CF' => 1,
    '85A0DD7DD720ADB7FF05F83D542B209DC7FF4528F7D677B18389FEA5E5C49E86' => 1,
    '8D722F81A9C113C0791DF136A2966DB26C950A971DB46B4199F4EA54B78BFB9F' => 1,
    '97552015F5DDFC3C8788C006944555408894450084F100867086BC1A2BB58DC8' => 1,
    '9ACFAB7E43C8D880D06B262A94DEEEE4B4659989C3D0CAF19BAF6405E41AB7DF' => 1,
    'BFD88FE1101C41AE3E801BF8BE56350EE9BAD1A6B9BD515EDC5C6D5B8711AC44' => 1,
    'C3846BF24B9E93CA64274C0EC67C1ECC5E024FFCACD2D74019350E81FE546AE4' => 1,
    'D7A7A0FB5D7E2731D771E9484EBCDEF71D5F0C3E0A2948782BC83EE0EA699EF4' => 1,
    'D8E0FEBC1DB2E38D00940F37D27D41344D993E734B99D5656D9778D4D8143624' => 1,
    'EBD41040E4BB3EC742C9E381D31EF2A41A48B6685C96E7CEF3C1DF6CD4331C99' => 1,
    'F1C1B50AE5A20DD8030EC9F6BC24823DD367B5255759B4E71B61FCE9F7375D73' => 1,
);

# Get the certificate issuer from a file.
my %cache = ();
sub get_issuer {
    my $hash = pop;
    my $file = "all/" . $hash;

    return $cache{$file} if defined $cache{$file};
    open my $fh, '<', $file or die "Can't open $file to find issuer, $!";
    while ( <$fh> ) {
	next unless s/.*Issuer: (.*)/$1/;
	close $fh;
	return $cache{$file} = $1 . ' [' . substr($hash, 0, 6) . '...]';
    }
    close $fh;
    return $file;
}

# Make a single list of all certs
rmtree("all") or die "Can't rmdir all, $!"
    if -d "all";
my %counts = ();
mkdir "all" or die "Can't mkdir, $!";
foreach my $DIR ( <certs.*> ) {
    chdir $DIR || die "Can't chdir $DIR, $!";
    my @files = <*>;
    my $who = $DIR;
    $who =~ s/^certs.//;
    $counts{$who} = scalar @files;
    foreach my $FILE ( @files ) {
	link $FILE, "../all/${FILE}" or die "Can't link $FILE, $!"
	    if ! -f "../all/${FILE}";
    }
    chdir ".." ||die "Can't chdir $DIR/.., $!";
}

chdir 'all' or die "Can't chdir all, $!";
my @all = <*>;
chdir '..' || die "Can'tchdir up, $!";
$counts{'all'} = scalar @all;

# Make list of certs that were grandfathered in.
my $gfcount = 0;
if ( !$justwrong ) {
    foreach my $file ( keys %grandfathered ) {
	$grandfathered{$file} = get_issuer($file);
	$gfcount++;
    }
}

# Make a list of our certs.
chdir "certs.akamai" or die "Can't chdir certs.akamai, $!";
my @akamai = <*>;
chdir ".." or die "Can't chdir .., $!";

# Make list of certs that should be in our trust-store but aren't.
my $misscount = 0;
my %missing = ();
if ( !$justwrong ) {
    foreach my $cert (
	grep {
	    -f "certs.apple/$_"
	    && -f "certs.google/$_"
	    && -f "certs.microsoft/$_"
	    && -f "certs.mozilla/$_"
	    && ! -f "certs.akamai/$_" } @all ) {
	$missing{$cert} = get_issuer($cert);
	$misscount++;
    }
}

# Make list of our certs that were don't follow policy.
my %wrong = ();
foreach my $cert (
    grep {
	! -f "certs.apple/$_" or
	! -f "certs.google/$_" or
	! -f "certs.microsoft/$_" or
	! -f "certs.mozilla/$_" } @akamai ) {
    $wrong{$cert} = get_issuer($cert)
			if not defined $grandfathered{$cert};
}

open my $FH, '>', 'index.html' or die "Can't open output, $!";
select $FH;

my $gf = $gfcount == 0
    ? ""
    : "\t<li><a href='#grandfathered'>Grandfathered Summary</a></li>\n";
my $mc = $misscount == 0
    ? ""
    : "\t<li><a href='#missing'>Missing Summary</a></li>";


print <<EOF;
<!DOCTYPE html>
<html lang="en">
  $head

  <body>
    <h1>Trust Store Comparison</h1>
    <p>This page generated at $now from scripts at <a href="$link">$link</a>.
    </p>
    <p>
    Contents
      <ul>
	<li><a href='#complete'>Complete Table</a></li>
	$mc
	$gf
	<li><a href='#wrong'>Wrongly-added Summary</a></li>
    </p>
    <p>Click on a column header to sort by that column.
    Double-Click to reverse-sort. Column headings:</p>
    <ul>
      <li>akamai - Akamai's global trust store</li>
      <li>apple - Apple's trust store</li>
      <li>google - Google's Chrome trust store</li>
      <li>microsoft - Microsoft's trust store</li>
      <li>mozilla - Firefox's trust store</li>
    </ul>

    <h2 id='complete'>Complete Table</h2>
    <table id="myTable" class="tablesorter" border='1'>
      <thead>
        <tr class="heading">
          <th>Issuer<br>&#8597; ($counts{'all'})</th>
EOF

# Print column headers.
foreach my $DIR ( <certs.*> ) {
    my $who = $DIR;
    $who =~ s/^certs.//;
    print "          <th>$who<br>&#8597;", $counts{$who}, "</th>\n";
}

print <<EOF;
          <th>#<br>&#8597; </th>
        </tr>
      </thead>

      <tbody>
EOF

# Make a reverse lookup, issuer->file
my @names;
my %n2f = ();
foreach my $FILE ( @all ) {
    my $iss = get_issuer($FILE);
    push @names, $iss;
    $n2f{$iss} = $FILE;
}

foreach my $ISS ( sort @names ) {
    my $FILE = $n2f{$ISS};
    my $VAL;
    my $COUNT = 0;
    next if $justwrong && !defined $wrong{$FILE};
    print "        <tr>\n";
    print "          <td><a target=\"_blank\" href=\"${CRTSH}${FILE}\">$ISS</a></br>\n";
    print "              ${MISSING}" if defined $missing{$FILE};
    print "              ${LEGACY}" if defined $grandfathered{$FILE};
    print "              ${WRONG}" if defined $wrong{$FILE};
    print "          </td>\n";
    foreach my $C ( <certs.*> ) {
	if ( -f "$C/$FILE" ) {
	    $VAL = $PRESENT;
	    $COUNT++;
	} else {
	    $VAL = $NOTPRESENT;
	}
        print "          $VAL</td>\n";
    }
    print "          <td width=\"$CW\">$COUNT</td>\n";
    print "        </tr>\n";
}

print <<EOF;
      </tbody>
    </table>
EOF

sub format_line {
    my $cert = shift;
    my $iss = shift;
    return "<li><a target=\"_blank\" href=\"${CRTSH}${cert}\">${iss}</a></br>\n";
}
sub format_list {
    my $hash_ref = shift;
    my %list = %{ $hash_ref };
    my @names = values %list;
    my $count = scalar @names;

    if ( $count == 0 ) {
	print "<p>None found.</p>\n";
	return;
    }
    print "<p>Number of certs = $count</p>\n";
    print "<ul>\n";
    foreach my $n ( sort @names ) {
	print "<li>"
	    . "<a target=\"_blank\" href=\"${CRTSH}$n2f{$n}\">${n}</a>"
	    . "</br></li>\n";
    }
    print "</ul>\n";
}

if ( $misscount != 0 ) {
    print "<h2 id='missing'>Missing Summary</h2>\n";
    format_list(\%missing);
}

if ( $gfcount != 0 ) {
    print "<h2 id='grandfathered'>Grandfathered Summary</h2>\n";
    format_list(\%grandfathered);
}

print "<h2 id='wrong'>Wrongly-added Summary</h2>\n";
format_list(\%wrong);

print <<EOF;
  </body>
</html>
EOF

select STDOUT;
close $FH;


open $FH, '>', $md or die "Can't open output, $!";
select $FH;

my $count = scalar @akamai;
print <<EOF;
# Akamai's Certificate Store

There are $count entries. Links below point to the full certificate
on https://crt.sh

EOF

my @trusted;
foreach my $file ( @akamai ) {
    push @trusted, get_issuer($file);
}

foreach my $n ( sort @trusted ) {
    my $file = "all/" . $n2f{$n};
    my $lines = `openssl x509 -noout -fingerprint -serial -enddate -in $file`;
    $lines =~ s/SHA1 Fingerprint=/  - Fingerprint /;
    $lines =~ s/serial=/  - Serial: /;
    $lines =~ s/notAfter=/  - Expires: /;
    my $link = "${CRTSH}" . $n2f{$n};
    print "- Name: [$n]($link)\n$lines\n";
}

select STDOUT;
close $FH;

#rmtree("all") or die "Can't rmdir all, $!"
#    if -d "all";

die "$repo does not exist -- update manually"
    if ! -d "$repo";

if ( compare($md, "$repo/$md") == 0 ) {
    print "No change to GitHub copy\n";
} else {
    copy($md, "$repo/$md") or die "Can't copy $md, $!";
    chdir "$repo" or die "Can't chdir $repo, $!";
    `git commit -m "Automatic update" $md`;
    `git push`;
}
